//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollMeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
        public string DayOfClass { get; set; }
        public string TimeOfClass { get; set; }
        public string Location { get; set; }
        public int InstructorId { get; set; }
    
        public virtual Instructors Instructor { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}
