//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollMeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructors
    {
        public Instructors()
        {
            this.Classes = new HashSet<Classes>();
        }
    
        public int InstructorId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Organization { get; set; }
    
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual Organizations Organizations { get; set; }
    }
}
